import Vue from "vue";
import VueRouter from "vue-router";

Vue.use(VueRouter);

const routes = [
  {
    path:"/",
    name:"home",
    component:()=>import("../views/Home.vue")
  },
  {
    path:"/two",
    name:"two",
    component:()=>import("../views/Two.vue")
  },
  {
    path:"/three",
    name:"three",
    component:()=>import("../views/Three.vue")
  },
  {
    path:"/four",
    name:"four",
    component:()=>import("../views/Four.vue")
  },
  {
    path:"/six",
    name:"six",
    component:()=>import("../views/Six.vue")
  },
  {
    path:"/seven",
    name:"seven",
    component:()=>import("../views/Seven.vue")
  },
  {
    path:"/share",
    name:"share",
    component:()=>import("../views/SevenShare.vue")
  },
  {
    path:"/nine",
    name:"nine",
    component:()=>import("../views/Nine.vue")
  },
  {
    path:"/list",
    name:"list",
    component:()=>import("../views/NineList.vue")
  },
  {
    path:"/ten",
    name:"ten",
    component:()=>import("../views/Ten.vue")
  },
  {
    path:"/shiyi",
    name:"shiyi",
    component:()=>import("../views/Shiyi.vue")
  },
  {
    path:"/shier",
    name:"shier",
    component:()=>import("../views/Shier.vue")
  },
  {
    path:"/shisan",
    name:"shisan",
    component:()=>import("../views/Shisan.vue")
  },
  {
    path:"/shisi",
    name:"shisi",
    component:()=>import("../views/Shisi.vue")
  },
  {
    path:"/shisilist",
    name:"shisilist",
    component:()=>import("../views/ShisiList.vue")
  },
  {
    path:"/shiwu",
    name:"shiwu",
    component:()=>import("../views/Shiwu.vue")
  },
  {
    path:"/shiliu",
    name:"shiliu",
    component:()=>import("../views/Shiliu.vue")
  },
  {
    path:"/shiba",
    name:"shiba",
    component:()=>import("../views/Shiba.vue")
  },
  {
    path:"/shiba2",
    name:"shiba2",
    component:()=>import("../views/Shiba2.vue")
  },
  {
    path:"/shiba3",
    name:"shiba3",
    component:()=>import("../views/Shiba3.vue")
  },
  {
    path:"/shijiu",
    name:"shijiu",
    component:()=>import("../views/Shijiu.vue")
  },
  {
    path:"/ershi",
    name:"ershi",
    component:()=>import("../views/Ershi.vue")
  },
];

const router = new VueRouter({
  routes,
});

export default router;
